# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.maintitle = QtWidgets.QLabel(self.centralwidget)
        self.maintitle.setGeometry(QtCore.QRect(320, 10, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.maintitle.setFont(font)
        self.maintitle.setTextFormat(QtCore.Qt.RichText)
        self.maintitle.setScaledContents(False)
        self.maintitle.setAlignment(QtCore.Qt.AlignCenter)
        self.maintitle.setObjectName("maintitle")
        self.x = QtWidgets.QLabel(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(380, 50, 31, 16))
        self.x.setObjectName("x")
        self.variance_x = QtWidgets.QSlider(self.centralwidget)
        self.variance_x.setEnabled(True)
        self.variance_x.setGeometry(QtCore.QRect(150, 50, 221, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.variance_x.sizePolicy().hasHeightForWidth())
        self.variance_x.setSizePolicy(sizePolicy)
        self.variance_x.setMinimumSize(QtCore.QSize(0, 0))
        self.variance_x.setSizeIncrement(QtCore.QSize(0, 0))
        self.variance_x.setBaseSize(QtCore.QSize(0, 0))
        self.variance_x.setMaximum(100)
        self.variance_x.setSingleStep(0)
        self.variance_x.setPageStep(0)
        self.variance_x.setOrientation(QtCore.Qt.Horizontal)
        self.variance_x.setTickInterval(0)
        self.variance_x.setObjectName("variance_x")
        self.title_x = QtWidgets.QLabel(self.centralwidget)
        self.title_x.setGeometry(QtCore.QRect(30, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_x.setFont(font)
        self.title_x.setAlignment(QtCore.Qt.AlignCenter)
        self.title_x.setObjectName("title_x")
        self.title_y = QtWidgets.QLabel(self.centralwidget)
        self.title_y.setGeometry(QtCore.QRect(20, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_y.setFont(font)
        self.title_y.setAlignment(QtCore.Qt.AlignCenter)
        self.title_y.setObjectName("title_y")
        self.variance_y = QtWidgets.QSlider(self.centralwidget)
        self.variance_y.setGeometry(QtCore.QRect(150, 90, 221, 21))
        self.variance_y.setMaximum(100)
        self.variance_y.setSingleStep(0)
        self.variance_y.setPageStep(0)
        self.variance_y.setOrientation(QtCore.Qt.Horizontal)
        self.variance_y.setObjectName("variance_y")
        self.title_z = QtWidgets.QLabel(self.centralwidget)
        self.title_z.setGeometry(QtCore.QRect(20, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_z.setFont(font)
        self.title_z.setAlignment(QtCore.Qt.AlignCenter)
        self.title_z.setObjectName("title_z")
        self.variance_z = QtWidgets.QSlider(self.centralwidget)
        self.variance_z.setGeometry(QtCore.QRect(150, 130, 221, 21))
        self.variance_z.setMaximum(100)
        self.variance_z.setSingleStep(0)
        self.variance_z.setPageStep(0)
        self.variance_z.setOrientation(QtCore.Qt.Horizontal)
        self.variance_z.setObjectName("variance_z")
        self.title_roll = QtWidgets.QLabel(self.centralwidget)
        self.title_roll.setGeometry(QtCore.QRect(450, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_roll.setFont(font)
        self.title_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.title_roll.setObjectName("title_roll")
        self.title_yaw = QtWidgets.QLabel(self.centralwidget)
        self.title_yaw.setGeometry(QtCore.QRect(450, 120, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_yaw.setFont(font)
        self.title_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.title_yaw.setObjectName("title_yaw")
        self.variance_roll = QtWidgets.QSlider(self.centralwidget)
        self.variance_roll.setGeometry(QtCore.QRect(530, 50, 221, 20))
        self.variance_roll.setMaximum(100)
        self.variance_roll.setSingleStep(0)
        self.variance_roll.setPageStep(0)
        self.variance_roll.setOrientation(QtCore.Qt.Horizontal)
        self.variance_roll.setObjectName("variance_roll")
        self.title_pitch = QtWidgets.QLabel(self.centralwidget)
        self.title_pitch.setGeometry(QtCore.QRect(450, 80, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_pitch.setFont(font)
        self.title_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.title_pitch.setObjectName("title_pitch")
        self.y = QtWidgets.QLabel(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(380, 90, 31, 16))
        self.y.setObjectName("y")
        self.z = QtWidgets.QLabel(self.centralwidget)
        self.z.setGeometry(QtCore.QRect(380, 130, 31, 16))
        self.z.setObjectName("z")
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(760, 50, 31, 16))
        self.roll.setObjectName("roll")
        self.pitch = QtWidgets.QLabel(self.centralwidget)
        self.pitch.setGeometry(QtCore.QRect(760, 90, 31, 16))
        self.pitch.setObjectName("pitch")
        self.yaw = QtWidgets.QLabel(self.centralwidget)
        self.yaw.setGeometry(QtCore.QRect(760, 130, 31, 16))
        self.yaw.setObjectName("yaw")
        self.title_lin_vel = QtWidgets.QLabel(self.centralwidget)
        self.title_lin_vel.setGeometry(QtCore.QRect(10, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_lin_vel.setFont(font)
        self.title_lin_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lin_vel.setObjectName("title_lin_vel")
        self.variance_linear_vel = QtWidgets.QSlider(self.centralwidget)
        self.variance_linear_vel.setGeometry(QtCore.QRect(240, 180, 191, 21))
        self.variance_linear_vel.setMaximum(100)
        self.variance_linear_vel.setSingleStep(0)
        self.variance_linear_vel.setPageStep(0)
        self.variance_linear_vel.setOrientation(QtCore.Qt.Horizontal)
        self.variance_linear_vel.setTickInterval(0)
        self.variance_linear_vel.setObjectName("variance_linear_vel")
        self.lin_vel = QtWidgets.QLabel(self.centralwidget)
        self.lin_vel.setGeometry(QtCore.QRect(440, 180, 31, 16))
        self.lin_vel.setObjectName("lin_vel")
        self.angular = QtWidgets.QLabel(self.centralwidget)
        self.angular.setGeometry(QtCore.QRect(440, 220, 31, 16))
        self.angular.setObjectName("angular")
        self.title_angular_vel = QtWidgets.QLabel(self.centralwidget)
        self.title_angular_vel.setGeometry(QtCore.QRect(10, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.title_angular_vel.setFont(font)
        self.title_angular_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.title_angular_vel.setObjectName("title_angular_vel")
        self.variance_angular_vel = QtWidgets.QSlider(self.centralwidget)
        self.variance_angular_vel.setGeometry(QtCore.QRect(240, 220, 191, 21))
        self.variance_angular_vel.setMaximum(100)
        self.variance_angular_vel.setSingleStep(0)
        self.variance_angular_vel.setPageStep(0)
        self.variance_angular_vel.setOrientation(QtCore.Qt.Horizontal)
        self.variance_angular_vel.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.variance_angular_vel.setTickInterval(0)
        self.variance_angular_vel.setObjectName("variance_angular_vel")
        self.variance_pitch = QtWidgets.QSlider(self.centralwidget)
        self.variance_pitch.setGeometry(QtCore.QRect(530, 90, 221, 20))
        self.variance_pitch.setMaximum(100)
        self.variance_pitch.setSingleStep(0)
        self.variance_pitch.setPageStep(0)
        self.variance_pitch.setOrientation(QtCore.Qt.Horizontal)
        self.variance_pitch.setObjectName("variance_pitch")
        self.variance_yaw = QtWidgets.QSlider(self.centralwidget)
        self.variance_yaw.setGeometry(QtCore.QRect(530, 130, 221, 20))
        self.variance_yaw.setMaximum(100)
        self.variance_yaw.setSingleStep(0)
        self.variance_yaw.setPageStep(0)
        self.variance_yaw.setOrientation(QtCore.Qt.Horizontal)
        self.variance_yaw.setObjectName("variance_yaw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuHEy = QtWidgets.QMenu(self.menubar)
        self.menuHEy.setObjectName("menuHEy")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHEy.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Variance Setter"))
        self.maintitle.setText(_translate("MainWindow", "Set the variance "))
        self.x.setText(_translate("MainWindow", "0"))
        self.title_x.setText(_translate("MainWindow", "X-Position"))
        self.title_y.setText(_translate("MainWindow", "Y-Position"))
        self.title_z.setText(_translate("MainWindow", "Z-Position"))
        self.title_roll.setText(_translate("MainWindow", "Roll"))
        self.title_yaw.setText(_translate("MainWindow", "Yaw"))
        self.title_pitch.setText(_translate("MainWindow", "Pitch"))
        self.y.setText(_translate("MainWindow", "0"))
        self.z.setText(_translate("MainWindow", "0"))
        self.roll.setText(_translate("MainWindow", "0"))
        self.pitch.setText(_translate("MainWindow", "0"))
        self.yaw.setText(_translate("MainWindow", "0"))
        self.title_lin_vel.setText(_translate("MainWindow", "Linear velocities"))
        self.lin_vel.setText(_translate("MainWindow", "0"))
        self.angular.setText(_translate("MainWindow", "0"))
        self.title_angular_vel.setText(_translate("MainWindow", "Angular velocities"))
        self.menuHEy.setTitle(_translate("MainWindow", "HEy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

